export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const importantLinks = [
    {
      title: "Privacy Policy",
      link: "/privacy-policy",
    },
    { title: "Terms + Conditions", link: "/terms-and-conditions" },
    { title: "Cookie Policy", link: "/cookie-policy" },
  ];

  return (
    <html lang="en">
      <body>{children}</body>

      <footer
        className={`mx-auto pt-7 pb-4 md:py-8 px-8 w-full max-w-7xl border-t-1 border-neutral-300 text-qrmory-purple-800`}
      >
        <section className={`mt-10`}>
          <h4 className={`md:hidden mb-4 font-bold text-lg text-center`}>
            Legal Information
          </h4>
          <ul
            className={`flex flex-col-reverse md:flex-row items-center gap-4`}
          >
            <li
              className={`mt-4 md:mt-0 pt-4 md:py-0.5 px-1 w-full md:w-fit border-t md:border-none text-sm text-neutral-400 text-center md:text-left`}
            >
              © 2025 QRmory. All rights reserved
            </li>
            {importantLinks.map((item, index) => (
              <li className={``} key={`important-link-${index}`}>
                <a
                  className="py-0.5 px-1 text-sm text-qrmory-purple-400 hover:text-white hover:bg-qrmory-purple-400 transition-all duration-500"
                  href={item.link}
                >
                  {item.title}
                </a>
              </li>
            ))}
          </ul>
        </section>
      </footer>
    </html>
  );
}
