import { LoginBlock } from "@/components/login-block";

export const metadata = {
  title: "Log in | QRmory",
  description: "Generated by Next.js",
};

export default function LogInPage() {
  return <LoginBlock />;
}
