import SignUpBlock from "@/components/sign-up-block";

export const metadata = {
  title: "Create a Free Account | QRmory",
  description: "Generated by Next.js",
};

export default function SignUpPage() {
  return <SignUpBlock />;
}
