import { LoginBlock } from "@/components/login-block";
import SignUpBlock from "@/components/sign-up-block";

export const metadata = {
  title: "Log in | QRmory",
  description: "Generated by Next.js",
};

export default function SignUpPage() {
  return <SignUpBlock />;
}
